<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="31" total="50" passed="19">
  <reporter-output>
    <line>
      <![CDATA[在：2018-01-18 12:53:28:341点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:53:32:586控件：com.thetiger.ziwork:id/phone_e不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:53:36:765点击了按钮：com.thetiger.ziwork:id/action_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:53:42:157输入了内容]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:53:48:113点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:53:52:298控件：com.thetiger.ziwork:id/edit_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:53:57:583控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:54:01:797控件：com.thetiger.ziwork:id/submit_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:54:35:750通过坐标点击]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:54:39:824控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:54:43:888控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:54:54:149重启了app]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:54:58:659点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:03:005控件：com.thetiger.ziwork:id/phone_e不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:06:753点击了按钮：com.thetiger.ziwork:id/action_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:12:606输入了内容]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:19:020点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:23:162控件：com.thetiger.ziwork:id/edit_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:28:808控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:33:204控件：com.thetiger.ziwork:id/submit_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:42:840点击了按钮：//android.widget.ImageButton[@content-desc='转到上一层级']]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:49:644控件：com.thetiger.ziwork:id/home_middle_banner不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:54:599通过坐标点击]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:55:59:037控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:03:172控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:07:198控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:11:530控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:15:833控件：com.thetiger.ziwork:id/main_tab_mine不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:20:120控件：com.thetiger.ziwork:id/zike_info_container不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:24:233控件：com.thetiger.ziwork:id/belong_city_siv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:28:362控件：com.thetiger.ziwork:id/confirm不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:32:501控件：com.thetiger.ziwork:id/work_time_siv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:36:647控件：com.thetiger.ziwork:id/confirm不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:41:535控件：//android.widget.TextView[@text='设计']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:45:698控件：com.thetiger.ziwork:id/click_to_select_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:50:639控件：//android.widget.TextView[@text='UI']不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:54:710控件：com.thetiger.ziwork:id/confirm_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:56:59:069控件：com.thetiger.ziwork:id/menu_common不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:03:167控件：com.thetiger.ziwork:id/content_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:07:339控件：com.thetiger.ziwork:id/menu_common不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:11:448控件：com.thetiger.ziwork:id/next_browse_action_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:23:107重启了app]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:27:022点击了按钮：com.thetiger.ziwork:id/phone_login_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:32:526输入了内容]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:36:494点击了按钮：com.thetiger.ziwork:id/action_tv]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:40:559控件：com.thetiger.ziwork:id/input_et不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:44:631控件：com.thetiger.ziwork:id/login_phone_tv不存在]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:57:54:044重启了app]]>
    </line>
    <line>
      <![CDATA[在：2018-01-18 12:58:19:845点击了按钮：com.thetiger.ziwork:id/wx_login_tv]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="313391" started-at="2018-01-18T04:53:13Z" finished-at="2018-01-18T04:58:26Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="313391" started-at="2018-01-18T04:53:13Z" finished-at="2018-01-18T04:58:26Z">
      <class name="com.Case.NewTest">
        <test-method status="PASS" signature="beforeSuite()[pri:0, instance:com.Case.NewTest@1f57539]" name="beforeSuite" is-config="true" duration-ms="7517" started-at="2018-01-18T12:53:05Z" finished-at="2018-01-18T12:53:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeSuite -->
        <test-method status="PASS" signature="BeforeClass()[pri:0, instance:com.Case.NewTest@1f57539]" name="BeforeClass" is-config="true" duration-ms="9301" started-at="2018-01-18T12:53:13Z" finished-at="2018-01-18T12:53:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- BeforeClass -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="1390" started-at="2018-01-18T12:53:26Z" data-provider="testing" finished-at="2018-01-18T12:53:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[注册(领新人礼包)]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即进入]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/novice_gift_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:28:341点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:28Z" finished-at="2018-01-18T12:53:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4243" started-at="2018-01-18T12:53:28Z" data-provider="testing" finished-at="2018-01-18T12:53:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[2]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入手机号码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_e]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[随机]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:32:586控件：com.thetiger.ziwork:id/phone_e不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4162" started-at="2018-01-18T12:53:32Z" data-provider="testing" finished-at="2018-01-18T12:53:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[3]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击获取验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:36:765点击了按钮：com.thetiger.ziwork:id/action_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:32Z" finished-at="2018-01-18T12:53:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="5391" started-at="2018-01-18T12:53:36Z" data-provider="testing" finished-at="2018-01-18T12:53:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[4]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/input_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:42:157输入了内容]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:36Z" finished-at="2018-01-18T12:53:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="5955" started-at="2018-01-18T12:53:42Z" data-provider="testing" finished-at="2018-01-18T12:53:48Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[5]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/title_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:48:113点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:42Z" finished-at="2018-01-18T12:53:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4186" started-at="2018-01-18T12:53:48Z" data-provider="testing" finished-at="2018-01-18T12:53:52Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[6]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入姓名]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/edit_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[自客123456]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:52:298控件：com.thetiger.ziwork:id/edit_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:48Z" finished-at="2018-01-18T12:53:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:52Z" finished-at="2018-01-18T12:53:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="5284" started-at="2018-01-18T12:53:52Z" data-provider="testing" finished-at="2018-01-18T12:53:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[7]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入职位]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.EditText[@text='如：文案达人']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[开发测试工程师]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:53:57:583控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4215" started-at="2018-01-18T12:53:57Z" data-provider="testing" finished-at="2018-01-18T12:54:01Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[8]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完成]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/submit_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/webview]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:54:01:797控件：com.thetiger.ziwork:id/submit_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:53:57Z" finished-at="2018-01-18T12:53:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="33951" started-at="2018-01-18T12:54:01Z" data-provider="testing" finished-at="2018-01-18T12:54:35Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[9]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击一键领取]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Strongclick]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:54:35:750通过坐标点击]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:54:01Z" finished-at="2018-01-18T12:54:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4075" started-at="2018-01-18T12:54:35Z" data-provider="testing" finished-at="2018-01-18T12:54:39Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[10]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击已购领取的小课]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:54:39:824控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:54:35Z" finished-at="2018-01-18T12:54:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4062" started-at="2018-01-18T12:54:39Z" data-provider="testing" finished-at="2018-01-18T12:54:43Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[11]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即播放]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/pause_btn]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:54:43:888控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:54:39Z" finished-at="2018-01-18T12:54:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:54:43Z" finished-at="2018-01-18T12:54:43Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="12260" started-at="2018-01-18T12:54:43Z" data-provider="testing" finished-at="2018-01-18T12:54:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[12]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[重启下app]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:54:54:149重启了app]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:54:56Z" finished-at="2018-01-18T12:54:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="2507" started-at="2018-01-18T12:54:56Z" data-provider="testing" finished-at="2018-01-18T12:54:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[13]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[注册(首页领新人福利)]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即进入]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/novice_gift_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:54:58:659点击了按钮：com.thetiger.ziwork:id/novice_gift_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4346" started-at="2018-01-18T12:54:58Z" data-provider="testing" finished-at="2018-01-18T12:55:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[14]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入手机号码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_e]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[随机]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:405)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:03:005控件：com.thetiger.ziwork:id/phone_e不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:54:58Z" finished-at="2018-01-18T12:54:58Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:55:03Z" finished-at="2018-01-18T12:55:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="3746" started-at="2018-01-18T12:55:03Z" data-provider="testing" finished-at="2018-01-18T12:55:06Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[15]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击获取验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:06:753点击了按钮：com.thetiger.ziwork:id/action_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:55:06Z" finished-at="2018-01-18T12:55:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="5853" started-at="2018-01-18T12:55:06Z" data-provider="testing" finished-at="2018-01-18T12:55:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[16]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/input_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:12:606输入了内容]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:55:12Z" finished-at="2018-01-18T12:55:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="6412" started-at="2018-01-18T12:55:12Z" data-provider="testing" finished-at="2018-01-18T12:55:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[17]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/title_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:19:020点击了按钮：com.thetiger.ziwork:id/login_phone_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:55:19Z" finished-at="2018-01-18T12:55:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4141" started-at="2018-01-18T12:55:19Z" data-provider="testing" finished-at="2018-01-18T12:55:23Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[18]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入姓名]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/edit_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[自客123456]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:23:162控件：com.thetiger.ziwork:id/edit_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:55:23Z" finished-at="2018-01-18T12:55:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="5644" started-at="2018-01-18T12:55:23Z" data-provider="testing" finished-at="2018-01-18T12:55:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[19]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[个人资料输入职位]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.EditText[@text='如：文案达人']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[开发测试工程师]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:28:808控件：//android.widget.EditText[@text='如：文案达人']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:28Z" finished-at="2018-01-18T12:55:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4397" started-at="2018-01-18T12:55:28Z" data-provider="testing" finished-at="2018-01-18T12:55:33Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[20]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完成]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/submit_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/webview]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:33:204控件：com.thetiger.ziwork:id/submit_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:33Z" finished-at="2018-01-18T12:55:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="9633" started-at="2018-01-18T12:55:33Z" data-provider="testing" finished-at="2018-01-18T12:55:42Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[21]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击返回，出现大弹窗]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.ImageButton[@content-desc='转到上一层级']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/home_banner_sdv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:42:840点击了按钮：//android.widget.ImageButton[@content-desc='转到上一层级']]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:42Z" finished-at="2018-01-18T12:55:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="2258" started-at="2018-01-18T12:55:42Z" data-provider="testing" finished-at="2018-01-18T12:55:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[22]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[出现弹窗，点掉]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/close_iv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[ispopup]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:45Z" finished-at="2018-01-18T12:55:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4545" started-at="2018-01-18T12:55:45Z" data-provider="testing" finished-at="2018-01-18T12:55:49Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[23]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击首页新人大礼包占位]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/home_middle_banner]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/webview]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:49:644控件：com.thetiger.ziwork:id/home_middle_banner不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:49Z" finished-at="2018-01-18T12:55:49Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4940" started-at="2018-01-18T12:55:49Z" data-provider="testing" finished-at="2018-01-18T12:55:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[24]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击一键领取]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Strongclick]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:54:599通过坐标点击]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:54Z" finished-at="2018-01-18T12:55:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4438" started-at="2018-01-18T12:55:54Z" data-provider="testing" finished-at="2018-01-18T12:55:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[25]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击已购领取的小课]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_target_view]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:55:59:037控件：com.thetiger.ziwork:id/guide_target_view不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:55:59Z" finished-at="2018-01-18T12:55:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4135" started-at="2018-01-18T12:55:59Z" data-provider="testing" finished-at="2018-01-18T12:56:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[26]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击立即播放]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/guide_bottom_ly]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/pause_btn]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:03:172控件：com.thetiger.ziwork:id/guide_bottom_ly不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4025" started-at="2018-01-18T12:56:03Z" data-provider="testing" finished-at="2018-01-18T12:56:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[27]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[注册完之后认证自客（认证两步流程）]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[返回到详情]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/course_back_iv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/bottom_play_btn]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:07:198控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:03Z" finished-at="2018-01-18T12:56:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:07Z" finished-at="2018-01-18T12:56:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4331" started-at="2018-01-18T12:56:07Z" data-provider="testing" finished-at="2018-01-18T12:56:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[28]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[返回到首页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/course_back_iv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:11:530控件：com.thetiger.ziwork:id/course_back_iv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:11Z" finished-at="2018-01-18T12:56:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4304" started-at="2018-01-18T12:56:11Z" data-provider="testing" finished-at="2018-01-18T12:56:15Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[29]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击我的]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_mine]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/collection_siv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:15:833控件：com.thetiger.ziwork:id/main_tab_mine不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:15Z" finished-at="2018-01-18T12:56:15Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4288" started-at="2018-01-18T12:56:15Z" data-provider="testing" finished-at="2018-01-18T12:56:20Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[30]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完善信息]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/zike_info_container]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:20:120控件：com.thetiger.ziwork:id/zike_info_container不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:20Z" finished-at="2018-01-18T12:56:20Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4110" started-at="2018-01-18T12:56:20Z" data-provider="testing" finished-at="2018-01-18T12:56:24Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[31]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击所在城市]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/belong_city_siv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:24:233控件：com.thetiger.ziwork:id/belong_city_siv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4129" started-at="2018-01-18T12:56:24Z" data-provider="testing" finished-at="2018-01-18T12:56:28Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[32]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击确定]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:28:362控件：com.thetiger.ziwork:id/confirm不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:24Z" finished-at="2018-01-18T12:56:24Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4139" started-at="2018-01-18T12:56:28Z" data-provider="testing" finished-at="2018-01-18T12:56:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[33]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击工作年限]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/work_time_siv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:32:501控件：com.thetiger.ziwork:id/work_time_siv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:28Z" finished-at="2018-01-18T12:56:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:32Z" finished-at="2018-01-18T12:56:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4146" started-at="2018-01-18T12:56:32Z" data-provider="testing" finished-at="2018-01-18T12:56:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[34]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击确定]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:36:647控件：com.thetiger.ziwork:id/confirm不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:36Z" finished-at="2018-01-18T12:56:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4889" started-at="2018-01-18T12:56:36Z" data-provider="testing" finished-at="2018-01-18T12:56:41Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[35]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击选择一个技能类别]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.TextView[@text='设计']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:41:535控件：//android.widget.TextView[@text='设计']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4161" started-at="2018-01-18T12:56:41Z" data-provider="testing" finished-at="2018-01-18T12:56:45Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[36]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击技能标签]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/click_to_select_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:45:698控件：com.thetiger.ziwork:id/click_to_select_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:41Z" finished-at="2018-01-18T12:56:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4941" started-at="2018-01-18T12:56:45Z" data-provider="testing" finished-at="2018-01-18T12:56:50Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[37]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击选择UI]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[//android.widget.TextView[@text='UI']]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:50:639控件：//android.widget.TextView[@text='UI']不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:45Z" finished-at="2018-01-18T12:56:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4072" started-at="2018-01-18T12:56:50Z" data-provider="testing" finished-at="2018-01-18T12:56:54Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[38]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击确定]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/confirm_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:54:710控件：com.thetiger.ziwork:id/confirm_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:50Z" finished-at="2018-01-18T12:56:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:54Z" finished-at="2018-01-18T12:56:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4357" started-at="2018-01-18T12:56:54Z" data-provider="testing" finished-at="2018-01-18T12:56:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[39]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击下一步]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:56:59:069控件：com.thetiger.ziwork:id/menu_common不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4099" started-at="2018-01-18T12:56:59Z" data-provider="testing" finished-at="2018-01-18T12:57:03Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[40]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入自我介绍]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/content_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[我是一个非常非常优秀的游戏达人]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:03:167控件：com.thetiger.ziwork:id/content_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:56:59Z" finished-at="2018-01-18T12:56:59Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:57:03Z" finished-at="2018-01-18T12:57:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4170" started-at="2018-01-18T12:57:03Z" data-provider="testing" finished-at="2018-01-18T12:57:07Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[41]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击完成，到成功页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/menu_common]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/next_browse_action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:07:339控件：com.thetiger.ziwork:id/menu_common不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:57:07Z" finished-at="2018-01-18T12:57:07Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4108" started-at="2018-01-18T12:57:07Z" data-provider="testing" finished-at="2018-01-18T12:57:11Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[42]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击去首页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/next_browse_action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:11:448控件：com.thetiger.ziwork:id/next_browse_action_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:57:11Z" finished-at="2018-01-18T12:57:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="13658" started-at="2018-01-18T12:57:11Z" data-provider="testing" finished-at="2018-01-18T12:57:25Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[43]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[ ]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[重启下app]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:23:107重启了app]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="1" started-at="2018-01-18T12:57:25Z" finished-at="2018-01-18T12:57:25Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="1915" started-at="2018-01-18T12:57:25Z" data-provider="testing" finished-at="2018-01-18T12:57:27Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[44]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[登录]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击手机号登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_login_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:27:022点击了按钮：com.thetiger.ziwork:id/phone_login_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="5504" started-at="2018-01-18T12:57:27Z" data-provider="testing" finished-at="2018-01-18T12:57:32Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[45]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入手机号码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/phone_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[13700000000]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:32:526输入了内容]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:57:27Z" finished-at="2018-01-18T12:57:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="3966" started-at="2018-01-18T12:57:32Z" data-provider="testing" finished-at="2018-01-18T12:57:36Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[46]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击获取验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/action_tv]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:36:494点击了按钮：com.thetiger.ziwork:id/action_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:57:32Z" finished-at="2018-01-18T12:57:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:57:36Z" finished-at="2018-01-18T12:57:36Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4065" started-at="2018-01-18T12:57:36Z" data-provider="testing" finished-at="2018-01-18T12:57:40Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[47]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[输入验证码]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/input_et]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[input]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[1111]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:408)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:40:559控件：com.thetiger.ziwork:id/input_et不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="17" started-at="2018-01-18T12:57:40Z" finished-at="2018-01-18T12:57:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="FAIL" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="4055" started-at="2018-01-18T12:57:40Z" data-provider="testing" finished-at="2018-01-18T12:57:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[48]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击登录，跳转首页]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/login_phone_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at org.testng.Assert.assertTrue(Assert.java:52)
	at com.test.Base.findEl(Base.java:231)
	at com.test.Base.dealData(Base.java:398)
	at com.Case.NewTest.testcase(NewTest.java:15)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:44:631控件：com.thetiger.ziwork:id/login_phone_tv不存在]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:57:44Z" finished-at="2018-01-18T12:57:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="11414" started-at="2018-01-18T12:57:44Z" data-provider="testing" finished-at="2018-01-18T12:57:56Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[49]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[重启下app]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[restart]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[F]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:57:54:044重启了app]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:57:56Z" finished-at="2018-01-18T12:57:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="testcase(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.Case.NewTest@1f57539]" name="testcase" duration-ms="23799" started-at="2018-01-18T12:57:56Z" data-provider="testing" finished-at="2018-01-18T12:58:19Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[50]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[微信登录]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[点击微信登录]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[com.thetiger.ziwork:id/wx_login_tv]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[click]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[com.thetiger.ziwork:id/main_tab_home]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[P]]>
              </value>
            </param>
          </params>
          <reporter-output>
            <line>
              <![CDATA[在：2018-01-18 12:58:19:845点击了按钮：com.thetiger.ziwork:id/wx_login_tv]]>
            </line>
          </reporter-output>
        </test-method> <!-- testcase -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.Case.NewTest@1f57539]" name="afterClass" is-config="true" duration-ms="6697" started-at="2018-01-18T12:58:19Z" finished-at="2018-01-18T12:58:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="failDeal()[pri:0, instance:com.Case.NewTest@1f57539]" name="failDeal" is-config="true" duration-ms="0" started-at="2018-01-18T12:58:19Z" finished-at="2018-01-18T12:58:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failDeal -->
        <test-method status="PASS" signature="afterSuite()[pri:0, instance:com.Case.NewTest@1f57539]" name="afterSuite" is-config="true" duration-ms="52" started-at="2018-01-18T12:58:26Z" finished-at="2018-01-18T12:58:26Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterSuite -->
      </class> <!-- com.Case.NewTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
